name: PHPMD

on: [push]

jobs:
  phpmd:
    name: PHPMD
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP environment
        uses: shivammathur/setup-php@v2
        with:
          coverage: none
          tools: phpmd

      - name: Run PHPMD
        run: |
          phpmd . github phpmd.ruleset.xml --exclude 'tests/*,vendor/*,bootstrap/*,public/*,storage/*' --suffixes php
        id: phpmd

      - name: Show PHPMD output
        run: |
          echo "${{ steps.phpmd.outputs.stdout }}"
          echo "Files affected by PHPMD:"
          grep -oP "FILE: \K.*" <<< "${{ steps.phpmd.outputs.stdout }}"
        if: ${{ steps.phpmd.outputs.stdout != '' }}
